name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up java
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jre

    - name: test
      run: ./mill cli.test

    - name: release
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        PUBLISH_CREDS: ${{ secrets.PUBLISH_CREDS }}
        SONATYPE_PGP_SECRET_KEY: ${{ secrets.SONATYPE_PGP_SECRET_KEY }}
      run: |
        echo ${SONATYPE_PGP_SECRET_KEY} > secret_key
        gpg --import --no-tty --batch --yes secret_key
        rm secret_key
        env VERSION=${GITHUB_REF} ./mill cli.publish --sonatypeCreds $PUBLISH_CREDS
