name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: graalvm@

      - name: test
        run: ./mill cli.test

      - name: release
        run: env VERSION=${GITHUB_REF:11} ./mill cli.publish --sonatypeCreds PUBLISH_CREDS --signed false --stagingRelease false
